// Item definitions extracted directly from the user's authentic 3D sprite sheet
export const ITEMS = {
  santa: { id: 'santa', name: '圣诞老人', img: './assets/items/santa.png' },
  snowman_green: { id: 'snowman_green', name: '绿帽雪人', img: './assets/items/snowman_green.png' },
  gift_pouch: { id: 'gift_pouch', name: '圣诞福袋', img: './assets/items/gift_pouch.png' },
  gnome: { id: 'gnome', name: '圣诞矮人', img: './assets/items/gnome.png' },
  reindeer: { id: 'reindeer', name: '圣诞麋鹿', img: './assets/items/reindeer.png' },
  snowman_yellow: { id: 'snowman_yellow', name: '黄帽雪人', img: './assets/items/snowman_yellow.png' },
  stocking: { id: 'stocking', name: '圣诞长袜', img: './assets/items/stocking.png' },
  xmas_pudding: { id: 'xmas_pudding', name: '圣诞布丁', img: './assets/items/xmas_pudding.png' },
  xmas_tree: { id: 'xmas_tree', name: '梦幻圣诞树', img: './assets/items/xmas_tree.png' },
  cookie_bucket: { id: 'cookie_bucket', name: '雪花饼干罐', img: './assets/items/cookie_bucket.png' },
  gift_green: { id: 'gift_green', name: '翠绿礼盒', img: './assets/items/gift_green.png' },
  gift_white: { id: 'gift_white', name: '蓝带白礼盒', img: './assets/items/gift_white.png' },
  gift_striped: { id: 'gift_striped', name: '红白条纹礼盒', img: './assets/items/gift_striped.png' },
  gift_yellow: { id: 'gift_yellow', name: '暖黄礼盒', img: './assets/items/gift_yellow.png' },
  nutcracker: { id: 'nutcracker', name: '胡桃夹子士兵', img: './assets/items/nutcracker.png' },
  bell: { id: 'bell', name: '圣诞金铃', img: './assets/items/bell.png' },
  snowman: { id: 'snowman', name: '欢乐雪人', img: './assets/items/snowman.png' },
  gift_box: { id: 'gift_box', name: '经典红礼盒', img: './assets/items/gift_box.png' },
  gift_round: { id: 'gift_round', name: '波纹圆礼盒', img: './assets/items/gift_round.png' },
  cocoa: { id: 'cocoa', name: '热可可杯', img: './assets/items/cocoa.png' },
  chips: { id: 'chips', name: '香脆薯片', img: './assets/items/chips.png' },
  bottle_pink: { id: 'bottle_pink', name: '粉色提手水壶', img: './assets/items/bottle_pink.png' },
  tumbler: { id: 'tumbler', name: '天蓝便携水壶', img: './assets/items/tumbler.png' },
  snack_bag: { id: 'snack_bag', name: '经典零食包', img: './assets/items/snack_bag.png' },
  can_bips: { id: 'can_bips', name: 'BIPS坚果黄罐', img: './assets/items/can_bips.png' },
  green_jar: { id: 'green_jar', name: '养生绿茶罐', img: './assets/items/green_jar.png' },
  milk: { id: 'milk', name: '鲜草莓甜奶', img: './assets/items/milk.png' },
  cleaner_blue: { id: 'cleaner_blue', name: '亮蓝洗护瓶', img: './assets/items/cleaner_blue.png' },
  coffee: { id: 'coffee', name: '秘制烘焙酱', img: './assets/items/coffee.png' },
  tub_bips: { id: 'tub_bips', name: 'BIPS奶酪桶', img: './assets/items/tub_bips.png' },
  kiwi_bottle: { id: 'kiwi_bottle', name: '奇异果酸奶', img: './assets/items/kiwi_bottle.png' },
  chocolate: { id: 'chocolate', name: '夹心脆巧克力', img: './assets/items/chocolate.png' },
  sport_orange: { id: 'sport_orange', name: '活力运动饮', img: './assets/items/sport_orange.png' },
  candle_striped: { id: 'candle_striped', name: '节日红白蜡烛', img: './assets/items/candle_striped.png' },
  red_tree: { id: 'red_tree', name: '红愿圣诞树', img: './assets/items/red_tree.png' },
  sport_red: { id: 'sport_red', name: '便携运动壶', img: './assets/items/sport_red.png' },
  syrup_brown: { id: 'syrup_brown', name: '浓缩焦糖浆', img: './assets/items/syrup_brown.png' },
  grape_water: { id: 'grape_water', name: '葡萄清凉饮', img: './assets/items/grape_water.png' },
  pure_water: { id: 'pure_water', name: '天然矿泉水', img: './assets/items/pure_water.png' },
  lemon_green: { id: 'lemon_green', name: '青柠苏打水', img: './assets/items/lemon_green.png' },
  lemon_soda: { id: 'lemon_soda', name: '柠檬果汁汽水', img: './assets/items/lemon_soda.png' },
  grape_soda: { id: 'grape_soda', name: '紫葡萄果汁', img: './assets/items/grape_soda.png' },
  jam_carrot: { id: 'jam_carrot', name: '蜜橙胡萝卜酱', img: './assets/items/jam_carrot.png' },
  jam_berry: { id: 'jam_berry', name: '蓝莓鲜果酱', img: './assets/items/jam_berry.png' },
  jam_peach: { id: 'jam_peach', name: '黄桃蜂蜜酱', img: './assets/items/jam_peach.png' },
  jam_lime: { id: 'jam_lime', name: '清甜青柠酱', img: './assets/items/jam_lime.png' },
  pudding_blue: { id: 'pudding_blue', name: '蓝莓慕斯桶', img: './assets/items/pudding_blue.png' },
  pudding_red: { id: 'pudding_red', name: '草莓布丁桶', img: './assets/items/pudding_red.png' },
  bear_bottle: { id: 'bear_bottle', name: '萌熊甜心饼', img: './assets/items/bear_bottle.png' },
  wreath: { id: 'wreath', name: '雪花饼干罐', img: './assets/items/cookie_bucket.png' },
  mitten: { id: 'mitten', name: '圣诞福袋', img: './assets/items/gift_pouch.png' }
};

export const ITEM_KEYS = Object.keys(ITEMS);
